### ISSUE TITLE
anisora

### ISSUE THREAD

**Issue by lingyu123-su** [zhenglinpan/Awesome-Animation-Research#4]
AniSora: Exploring the Frontiers of Animation Video Generation in the Sora Era  这篇工作似乎不是综述

初步看下来，这个是bilibili自己的一个项目，参考了视频生成里的open-sora相关的一些训练流程，用了他们自己收集的一个高质量的10M左右量级的数据集，在大规模集群上训练出来了一个模型，和ToonCrafter类似，应该是现在动漫生成里面最大的模型了，可惜不开源

**Comment by zhenglinpan** [comment]
Thanks for pointing that out! I will modify the categories.
